;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-scope-operator
        delete-horizontal-space
        ignore
        isearch-forward-word
        kill-rectangle
        kill-region
        multiple-cursors-mode
        org-self-insert-command
        transpose-words
        undefined
        wdired-finish-edit
        wdired-next-line
        wgrep-finish-edit
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        clang-format-region
        compile-goto-error
        describe-key
        handle-switch-frame
        isearch-forward-word
        org-return
        yaml-electric-dash-and-dot
        yas-expand
        ))
