;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        isearch-forward-word
        kill-rectangle
        kill-region
        transpose-words
        wgrep-finish-edit
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        ))
